server:
  port: 7999

spring:
  application:
    name: internsathi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/internsathi
    username: postgres
    password: 8956

  mail:
    host: smtp.gmail.com
    port: 587
    username: ajaymaharjan0007@gmail.com
    password: gdlxabqhpteinymu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      data-locations: classpath:/db/data.sql
      mode: embedded

